environments:
  default:
    env_vars:
      DROOLS_BUILD_MVN_OPTS: -Dfull
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      DROOLS_BUILD_MVN_OPTS: -Dfull
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    enabled: false
    env_vars:
      QUARKUS_BRANCH: main
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - quarkus
  quarkus-3:
    pull_request_default_check: false
    env_vars:
      BUILD_MAVEN_TOOL: maven_3.9.3
      BUILD_JDK_TOOL: jdk_17_latest
      BUILD_MVN_OPTS: -Denforcer.skip
      # DROOLS_BUILD_MVN_OPTS: -Dfull #  "No enabled as it does not compile in quarkus-3
      # BUILD_MVN_OPTS_QUARKUS_UPDATE: -Dfull
    ids:
    - quarkus
    - quarkus3
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '2.16'
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - quarkus
  sonarcloud:
    auto_generation: false
    env_vars:
      ENABLE_SONARCLOUD: true
      DROOLS_BUILD_MVN_OPTS: -Dfull
    ids:
    - sonarcloud
    - coverage
disable:
  triggers: true # TODO to set back
repositories:
- name: drools
- name: drools-website
- name: kie-benchmarks
  author:
    name: radtriste # TODO set back. Could not push to kiegroup
# - name: kie-jpmml-integration ## TODO to check if should be enabled
git:
  author:
    name: apache
    # Taken from https://ci-builds.apache.org/credentials/
    # Need to be verified
    credentials_id: 399061d0-5ab5-4142-a186-a52081fef742
    token_credentials_id: ci-builds
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: drools
    file_path: .ci/buildchain-config.yaml
maven:
  settings_file_id: kie-release-settings
  nexus:
    release_url: TO_DEFINE
    release_repository: TO_DEFINE
    staging_profile_url: TO_DEFINE
    staging_profile_id: TO_DEFINE
    build_promotion_profile_id: TO_DEFINE
  artifacts_repository: ''
  artifacts_upload_repository:
    url: TO_DEFINE
    creds_id: TO_DEFINE
cloud:
  image:
    registry_credentials: tradisso_registry_token # TODO set to `kogito-quay-token`
    registry: quay.io
    namespace: tradisso
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        image: quay.io/kiegroup/kogito-ci-build:latest
        args: -v /var/run/docker.sock:/var/run/docker.sock --group-add docker --group-add input --group-add render
  default_tools:
    jdk: jdk_11_latest
    maven: maven_3.8.6
    sonar_jdk: jdk_17_latest
