generation_config:
  missing_environment: ignore
environments:
  default:
    env_vars:
      BUILD_MVN_OPTS: -Denforcer.skip
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS: -Denforcer.skip
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    enabled: false
    env_vars:
      QUARKUS_BRANCH: main
      BUILD_MVN_OPTS: -Denforcer.skip
    ids:
    - quarkus
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '3.0'
      BUILD_MVN_OPTS: -Denforcer.skip
    ids:
    - quarkus
  quarkus-lts:
    enabled: false
    pull_request_default_check: false
    env_vars:
      QUARKUS_BRANCH: '3.2'
      BUILD_MVN_OPTS: -Dproductized -Ddata-index-ephemeral.image=quay.io/kiegroup/kogito-data-index-ephemeral -Denforcer.skip
    ids:
    - quarkus
    - lts
    - prod
  native-lts:
    enabled: false
    env_vars:
      NATIVE: true
      QUARKUS_BRANCH: '3.2'
      BUILD_MVN_OPTS: -Dproductized -Ddata-index-ephemeral.image=quay.io/kiegroup/kogito-data-index-ephemeral -Denforcer.skip
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
      BUILD_ENVIRONMENT: quarkus-lts
    ids:
    - native
    - prod
  sonarcloud:
    enabled: false
    auto_generation: false
    env_vars:
      ENABLE_SONARCLOUD: false
      BUILD_MVN_OPTS: -Denforcer.skip
    ids:
    - sonarcloud
    - coverage
productized_branch: false
disable:
  triggers: false
repositories:
- name: drools
  branch: 9.44.x
- name: kie-jpmml-integration
  branch: 9.44.x
productized_repositories:
- name: drools
git:
  author:
    name: kiegroup
    credentials_id: kie-ci4
    token_credentials_id: kie-ci4-token
  bot_author:
    name: bsig-gh-bot
    credentials_id: bsig-gh-bot
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: drools
    branch: main
    file_path: .ci/buildchain-config.yaml
maven:
  settings_file_id: kogito_release_settings
  nexus:
    release_url: https://repository.jboss.org/nexus
    release_repository: jboss-releases-repository
    staging_profile_url: https://repository.jboss.org/nexus/content/groups/kogito-public/
    staging_profile_id: 1976dd1c18392a
    build_promotion_profile_id: ea49ccd6f174
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.jboss.org/nexus/content/repositories/snapshots/
    creds_id: kogito-snapshots-upload
  pr_checks:
    repository:
      url: https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/repositories/kogito-runtimes-pr-full-testing/
      creds_id: unpacks-zip-on-qa-nexus
cloud:
  image:
    registry_credentials_nightly: nightly_kogito
    registry_credentials_release: release_kogito
    registry: quay.io
    namespace: kiegroup
    latest_git_branch: main
jenkins:
  email_creds_id: KOGITO_CI_EMAIL_TO
  default_tools:
    jdk: kie-jdk17
    maven: kie-maven-3.8.7
