name: Drools Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  drools-build:
    concurrency:
      group: drools_pr-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        maven-version: ['3.8.1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Clean Disk Space
        uses: ginxo/kogito-pipelines/.ci/actions/ubuntu-disk-space@BXMSPROD-1540
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ginxo/kogito-pipelines/.ci/actions/long-paths@BXMSPROD-1540
      - name: Java and Maven Setup
        uses: ginxo/kogito-pipelines/.ci/actions/java@BXMSPROD-1540
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
      - name: Cache Maven
        uses: ginxo/kogito-pipelines/.ci/actions/cache-maven@BXMSPROD-1540
        with:
          key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: ginxo/kogito-pipelines/.ci/actions/build-chain@BXMSPROD-1540
        with:
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Surefire Report
        uses: ginxo/kogito-pipelines/.ci/actions/surefire-report@BXMSPROD-1540
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
