# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Jenkins Tests
on:
  pull_request:
    paths: 
    - '.ci/jenkins/**'
    - '.github/workflows/jenkins-tests-PR.yml'

jobs:
  dsl-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup correct base branch
      run: |
        base_branch="${{ github.base_ref }}"
        if [[ ${base_branch} =~ ^[0-9]+\.[0-9]+\.x$ ]]; then 
          IFS='.' read -ra ver <<< "${base_branch}"
          release=${ver[2]}
          minor=${ver[1]}
          major=${ver[0]}
          base_branch="$((major+7)).$minor.$release"
        fi
        echo "BRANCH_CONFIG_NAME=${base_branch}" >> $GITHUB_ENV

    - name: DSL tests
      uses: kiegroup/kogito-pipelines/.ci/actions/dsl-tests@main
      with:
        main-config-file-repo: kiegroup/kogito-pipelines
        main-config-file-ref: main
        main-config-file-path: dsl/config/main.yaml
        branch-config-name: ${{ env.BRANCH_CONFIG_NAME }}