name: Kogito Downstream

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  kogito-downstream-build:
    concurrency:
      group: pr-${{ matrix.job_name }}_${{ matrix.os }}_${{ matrix.java-version }}_${{ matrix.maven-version }}_${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 180
    strategy:
      matrix:
        job_name: [ kogito-runtimes, kogito-apps, serverless-workflow-examples ]
        os: [ubuntu-latest]
        java-version: [17]
        maven-version: ['3.9.6']
        include:
          - job_name: kogito-runtimes
            repository: kogito-runtimes
          - job_name: kogito-apps
            repository: kogito-apps
            env_BUILD_MVN_OPTS: "-DskipUI"
          - job_name: serverless-workflow-examples
            repository: kogito-examples
            env_KOGITO_EXAMPLES_SUBFOLDER_POM: serverless-workflow-examples/
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.job_name }} (${{ matrix.os }} / Java-${{ matrix.java-version }} / Maven-${{ matrix.maven-version }})
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kie-ci/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: kiegroup/kie-ci/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kie-ci/.ci/actions/build-chain@main
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/drools/${BRANCH:main}/.ci/buildchain-config.yaml
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          starting-project: kiegroup/${{ matrix.repository }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        env: 
          BUILD_MVN_OPTS: ${{ matrix.env_BUILD_MVN_OPTS }}
          KOGITO_EXAMPLES_SUBFOLDER_POM: ${{ matrix.env_KOGITO_EXAMPLES_SUBFOLDER_POM }}
      - name: Surefire Report
        uses: kiegroup/kie-ci/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
